<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Liga extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Liga_model');
    } 

    /*
     * Listing of liga
     */
    function index()
    {
        $data['liga'] = $this->Liga_model->get_all_liga();

        $this->load->view('liga/index',$data);
    }

    /*
     * Adding a new liga
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
		$this->form_validation->set_rules('numplazasdisp','Numplazasdisp','required|integer');
		$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'numjugadores' => $this->input->post('numjugadores'),
				'numplazasdisp' => $this->input->post('numplazasdisp'),
				'numtemporadas' => $this->input->post('numtemporadas'),
            );
            
            $liga_id = $this->Liga_model->add_liga($params);
            redirect('liga/index');
        }
        else
        {
            $this->load->view('liga/add');
        }
    }  

    /*
     * Editing a liga
     */
    function edit($id)
    {   
        // check if the liga exists before trying to edit it
        $liga = $this->Liga_model->get_liga($id);
        
        if(isset($liga['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
			$this->form_validation->set_rules('numplazasdisp','Numplazasdisp','required|integer');
			$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'numjugadores' => $this->input->post('numjugadores'),
					'numplazasdisp' => $this->input->post('numplazasdisp'),
					'numtemporadas' => $this->input->post('numtemporadas'),
                );

                $this->Liga_model->update_liga($id,$params);            
                redirect('liga/index');
            }
            else
            {   
                $data['liga'] = $this->Liga_model->get_liga($id);
    
                $this->load->view('liga/edit',$data);
            }
        }
        else
            show_error('The liga you are trying to edit does not exist.');
    } 

    /*
     * Deleting liga
     */
    function remove($id)
    {
        $liga = $this->Liga_model->get_liga($id);

        // check if the liga exists before trying to delete it
        if(isset($liga['id']))
        {
            $this->Liga_model->delete_liga($id);
            redirect('liga/index');
        }
        else
            show_error('The liga you are trying to delete does not exist.');
    }
    
}
