<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Liga extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Liga_model');
        $this->load->model('Juego_model');
        $this->load->model('Ranking_model');
    } 

    /*
     * Listing of liga
     */
    function index()
    {
        $data['liga'] = $this->Liga_model->get_all_liga();
        $this->load->view('liga/index',$data);
    }

    /*
     * Adding a new liga
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
		$this->form_validation->set_rules('numplazasdisp','Numplazasdisp','required|integer');
		$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');
        $this->form_validation->set_rules('nombre','Nombre','required|max_length[40]');

		
		if($this->form_validation->run())     
        {   
            $params = array(
				'numjugadores' => $this->input->post('numjugadores'),
				'numplazasdisp' => $this->input->post('numplazasdisp'),
				'numtemporadas' => $this->input->post('numtemporadas'),
                'nombre' => $this->input->post('nombre'),
                'idJuego' => $this->input->post('idJuego'),
                'idRanking' => $this->input->post('idRanking')
            );
            $liga_id = $this->Liga_model->add_liga($params);
            $data['liga'] = $this->Liga_model->get_all_liga();

            $this->load->view('Backoffice/Liga/index',$data);
        }
        else
        {
            $data['Juegos'] = $this->Juego_model->get_all_juego();
            $data['Rankings'] = $this->Ranking_model->get_all_ranking();
            $this->load->view('Backoffice/liga/add',$data);
        }
    }

    /*
     * Editing a liga
     */
    function edit($id)
    {   
        // check if the liga exists before trying to edit it
        $liga = $this->Liga_model->get_liga($id);
        
        if(isset($liga['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
			$this->form_validation->set_rules('numplazasdisp','Numplazasdisp','required|integer');
			$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');
            $this->form_validation->set_rules('nombre','Nombre','required|max_length[40]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'numjugadores' => $this->input->post('numjugadores'),
					'numplazasdisp' => $this->input->post('numplazasdisp'),
					'numtemporadas' => $this->input->post('numtemporadas'),
                    'nombre' => $this->input->post('nombre'),
                );

                $this->Liga_model->update_liga($id,$params);
                $data['liga'] = $this->Liga_model->get_all_liga();

                $this->load->view('Backoffice/Liga/index',$data);
            }
            else
            {   
                $data['liga'] = $this->Liga_model->get_liga($id);
                $data['Juegos'] = $this->Juego_model->get_all_juego();
                $data['Rankings'] = $this->Ranking_model->get_all_ranking();
                $this->load->view('liga/edit',$data);
            }
        }
        else
            show_error('The liga you are trying to edit does not exist.');
    } 

    /*
     * Deleting liga
     */
    function remove($id)
    {
        $liga = $this->Liga_model->get_liga($id);

        // check if the liga exists before trying to delete it
        if(isset($liga['id']))
        {
            $this->Liga_model->delete_liga($id);
            $data['liga'] = $this->Liga_model->get_all_liga();
            $this->load->view('Backoffice/Liga/index',$data);
        }
        else
            show_error('The liga you are trying to delete does not exist.');
    }
    
}
