<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Torneo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Torneo_model');
        $this->load->model('Juego_model');
    } 

    /*
     * Listing of torneo
     */
    function index()
    {
        $data['torneo'] = $this->Torneo_model->get_all_torneo();

        $this->load->view('torneo/index',$data);
    }

    /*
     * Adding a new torneo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
		$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');

		if($this->form_validation->run())     
        {   
            $params = array(
				'numjugadores' => $this->input->post('numjugadores'),
				'numtemporadas' => $this->input->post('numtemporadas'),
                'juego' => $_POST['Juego'],
                '1Premio' => $this->input->post('1Premio'),
                '2Premio' => $this->input->post('2Premio'),
                '3Premio' => $this->input->post('3Premio'),
            );
            
            $torneo_id = $this->Torneo_model->add_torneo($params);
            $data['Torneos'] = $this->Torneo_model->get_all_torneo();
            $this->load->view('Backoffice/Torneo/index',$data);
        }
        else
        {
            $data['Juegos'] = $this->Juego_model->get_all_juego();
            $this->load->view('Backoffice/Torneo/add',$data);
        }
    }  

    /*
     * Editing a torneo
     */
    function edit($id)
    {   
        // check if the torneo exists before trying to edit it
        $torneo = $this->Torneo_model->get_torneo($id);
        
        if(isset($torneo['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('numjugadores','Numjugadores','required|integer');
			$this->form_validation->set_rules('numtemporadas','Numtemporadas','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'numjugadores' => $this->input->post('numjugadores'),
                    'numtemporadas' => $this->input->post('numtemporadas'),
                    'juego' => $_POST['Juego'],
                    '1Premio' => $this->input->post('1Premio'),
                    '2Premio' => $this->input->post('2Premio'),
                    '3Premio' => $this->input->post('3Premio'),
                );

                $this->Torneo_model->update_torneo($id,$params);
                $data['Torneos'] = $this->Torneo_model->get_all_torneo();
                $this->load->view('Backoffice/Torneo/index',$data);
            }
            else
            {   
                $data['torneo'] = $this->Torneo_model->get_torneo($id);
                $data['Juegos'] = $this->Juego_model->get_all_juego();
                $this->load->view('torneo/edit',$data);
            }
        }
        else
            show_error('The torneo you are trying to edit does not exist.');
    } 

    /*
     * Deleting torneo
     */
    function remove($id)
    {
        $torneo = $this->Torneo_model->get_torneo($id);

        // check if the torneo exists before trying to delete it
        if(isset($torneo['id']))
        {
            $this->Torneo_model->delete_torneo($id);
            $data['Torneos'] = $this->Torneo_model->get_all_torneo();
            $this->load->view('Backoffice/Torneo/index',$data);
        }
        else
            show_error('The torneo you are trying to delete does not exist.');
    }
    
}
