<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Juego_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get juego by id
     */
    function get_juego($id)
    {
        return $this->db->get_where('juego',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all juego
     */
    function get_all_juego()
    {
        return $this->db->get('juego')->result_array();
    }
    
    /*
     * function to add new juego
     */
    function add_juego($params)
    {
        $this->db->insert('juego',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update juego
     */
    function update_juego($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('juego',$params);
        if($response)
        {
            return "juego updated successfully";
        }
        else
        {
            return "Error occuring while updating juego";
        }
    }
    
    /*
     * function to delete juego
     */
    function delete_juego($id)
    {
        $response = $this->db->delete('juego',array('id'=>$id));
        if($response)
        {
            return "juego deleted successfully";
        }
        else
        {
            return "Error occuring while deleting juego";
        }
    }
}
