<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Liga_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get liga by id
     */
    function get_liga($id)
    {
        return $this->db->get_where('liga',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all liga
     */
    function get_all_liga()
    {
        return $this->db->get('liga')->result_array();
    }
    
    /*
     * function to add new liga
     */
    function add_liga($params)
    {
        $this->db->insert('liga',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update liga
     */
    function update_liga($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('liga',$params);
        if($response)
        {
            return "liga updated successfully";
        }
        else
        {
            return "Error occuring while updating liga";
        }
    }
    
    /*
     * function to delete liga
     */
    function delete_liga($id)
    {
        $response = $this->db->delete('liga',array('id'=>$id));
        if($response)
        {
            return "liga deleted successfully";
        }
        else
        {
            return "Error occuring while deleting liga";
        }
    }
}
