<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Ranking_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ranking by id
     */
    function get_ranking($id)
    {
        return $this->db->get_where('ranking',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all ranking
     */
    function get_all_ranking()
    {
        return $this->db->get('ranking')->result_array();
    }
    
    /*
     * function to add new ranking
     */
    function add_ranking($params)
    {
        $this->db->insert('ranking',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ranking
     */
    function update_ranking($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('ranking',$params);
        if($response)
        {
            return "ranking updated successfully";
        }
        else
        {
            return "Error occuring while updating ranking";
        }
    }
    
    /*
     * function to delete ranking
     */
    function delete_ranking($id)
    {
        $response = $this->db->delete('ranking',array('id'=>$id));
        if($response)
        {
            return "ranking deleted successfully";
        }
        else
        {
            return "Error occuring while deleting ranking";
        }
    }
}
