<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Torneo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get torneo by id
     */
    function get_torneo($id)
    {
        return $this->db->get_where('torneo',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all torneo
     */
    function get_all_torneo()
    {
        return $this->db->get('torneo')->result_array();
    }
    
    /*
     * function to add new torneo
     */
    function add_torneo($params)
    {
        $this->db->insert('torneo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update torneo
     */
    function update_torneo($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('torneo',$params);
        if($response)
        {
            return "torneo updated successfully";
        }
        else
        {
            return "Error occuring while updating torneo";
        }
    }
    
    /*
     * function to delete torneo
     */
    function delete_torneo($id)
    {
        $response = $this->db->delete('torneo',array('id'=>$id));
        if($response)
        {
            return "torneo deleted successfully";
        }
        else
        {
            return "Error occuring while deleting torneo";
        }
    }
}
